/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.abc;

import static org.testng.Assert.*;

import org.testng.annotations.Test;

public class PersonTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Person testPerson = new Person();
        assertTrue(testPerson.id == 1, "default id value");
    }
}
