/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.abc;

import org.testng.Assert;
import org.testng.annotations.Test;


public class PersonTest {
    @Test public void defaultIdTest() {
        Person testPerson = new Person();
        Assert.assertTrue(testPerson.id == 1, "default id value");
    }

    @Test public void ageTest() {
        Person testPerson = new Person();
        Assert.assertTrue(testPerson.age(testPerson.birth) == 19, "default id value");
    }
}
